// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qoqxsswtkejtwtelugrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvcXhzc3d0a2VqdHd0ZWx1Z3JrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMTExNjYsImV4cCI6MjA2MDc4NzE2Nn0.TaZN9-ZQhZfJm5Jg9umzfZIUB7TBiNXnEqjxPUkyI4k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);